export const fruits = [
  'mącznica',
  'morela',
  'jagoda',
  'flaszowiec',
  'rambutan',
  'jabłko',
  'liczi',
  'nektarynka',
  'jagoda kamczacka',
  'malina',
  'awokado',
  'mandarynka',
  'jujuba',
  'tarnina',
  'wiśnia',
  'pitaja',
  'makadamia',
  'morwa',
  'poziomka',
  'kokos',
  'śliwka',
  'gac',
  'żurawina',
  'limonka',
  'orzeszki buku',
  'abiu',
  'banan',
  'orzech laskowy',
  'głóg',
  'ananas',
  'cytryna',
  'agrest',
  'kasztan jadalny',
  'aronia',
  'borówka',
  'mangostan',
  'winogrono',
  'gewuina',
  'orzech ziemny',
  'biała porzeczka',
  'dzika róża',
  'pekan',
  'jarzębina',
  'durian',
  'oskomian',
  'kawon',
  'orzech włoski',
  'dżakfrut',
  'jeżyna',
  'moroszka',
  'brusznica',
  'rokitnik',
  'mongongo',
  'czarny bez',
  'tamarillo',
  'orzeszki sosny koreańskiej',
  'pistacja',
  'czarna porzeczka',
  'granat',
  'brzoskwinia',
  'piniole',
  'kamionka',
  'muszpla',
  'kumkwat',
  'daktyl',
  'arbuz',
  'czereśnia',
  'łochynia',
  'mahonia',
  'figa',
  'migdał',
  'kiwi',
  'borówka amerykańska',
  'nieszpułka',
  'opuncja',
  'nerkowiec',
  'czerwona porzeczka',
  'orzech brazylijski',
  'czeremcha',
  'persymona',
  'grejpfrut',
  'kawon',
  'pigwa',
  'amla',
  'truskawka',
  'szypszyna',
  'gruszka',
  'kleiszcze smakowite',
  'dereń',
  'papaja',
  'mango',
  'melon',
  'pomarańcza',
];

export const letters = [
  'A',
  'Ą',
  'B',
  'C',
  'Ć',
  'D',
  'E',
  'Ę',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'Ł',
  'M',
  'N',
  'Ń',
  'O',
  'Ó',
  'P',
  'R',
  'S',
  'Ś',
  'T',
  'U',
  'W',
  'Y',
  'Z',
  'Ź',
  'Ż',
];

var cart = ['banan', 'jabłko']; //czyli w koszyku mamy dwa owoce, ilość sztuk można sprawdzić w tablicy ze sztukami

var cartQuantities = new Map(); //cartQuantities jest mapą. Mapa to w JS coś pomiędzy tablicą a obiektem, pozwala na przechowywanie wartości pod nazwą
// https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/Map
//generalnie jak masz mapę to masz kilka funckji:
//Map.set(key, value) - ustawia wartość value dla klucza key
//Map.get(key) - pobiera i zwraca z mapy wartość dla klucz key (jak nie ma takiego to zwróci undefined)
//Map.has(key) - zwraca true/false czy mapa ma obecnie zdefiniowany klucz (i wartość) key
//Map.delete(key) - usuwa wartość i klucz key (zwraca true/false czy sie udało czy nie)

//więc do quantity byś miał np. tak
//dodawanie:
cartQuantities.set('banan', 23); //ustawienie ilości sztuk banana na 23
cartQuantities.get('banan'); //pobranie ilości sztuk banana w koszyku
cartQuantities.delete('banan'); //usunięcie info i ilości sztuk banana z koszyka (przydatne przy usuwaniu owoca z kosz
